version: '3.0'

services:
  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
    hostname: oauth2-proxy
    ports:
      - 4180:4180

    command: --config /oauth2-proxy.cfg
    volumes:
      - "./oauth2-proxy.cfg:/oauth2-proxy.cfg"

  appweb:
    container_name: appweb
    hostname: appweb
    build: ./web
    ports:
     - 3000:3000

  api:
    container_name: api
    hostname: api
    build: ./api
    ports:
     - 3003:3003
    